"""Configuration management for the ``trs`` CLI / SDK.

The config file lives at ``~/.config/theroom/config.toml`` (overridable via
``TRS_CONFIG`` env var) and contains one or more named *profiles*.  Each
profile stores a base URL plus an optional API token.  The active profile
defaults to ``default`` and may be overridden by ``--profile`` on the CLI or
the ``TRS_PROFILE`` environment variable.
"""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - 3.10 fallback
    import tomli as tomllib  # type: ignore[no-redef]


CONFIG_ENV = "TRS_CONFIG"
PROFILE_ENV = "TRS_PROFILE"
DEFAULT_PROFILE = "default"
APP_NAME = "theroom"


def _config_path() -> Path:
    """Return the path to the user's config file.

    Honours ``$TRS_CONFIG`` first; falls back to ``$XDG_CONFIG_HOME``/theroom
    or ``~/.config``/theroom on POSIX, and ``%APPDATA%``/theroom on Windows.
    """
    env = os.environ.get(CONFIG_ENV)
    if env:
        return Path(env).expanduser()
    if os.name == "nt":
        base = os.environ.get("APPDATA") or str(Path.home() / "AppData" / "Roaming")
    else:
        base = os.environ.get("XDG_CONFIG_HOME") or str(Path.home() / ".config")
    return Path(base) / APP_NAME / "config.toml"


@dataclass
class Profile:
    """A single named profile."""

    name: str
    base_url: str = "http://127.0.0.1:8000"
    token: str = ""
    api_key: str = ""
    # ``room_cookie`` is the value of the ``room_session`` cookie.  Some
    # browser-cookie-only endpoints (file upload, messages, share) need
    # it on every request, so we let the CLI persist it alongside the
    # API token.  The SDK / API don't care about it.
    room_cookie: str = ""
    # Free-form extras (e.g. default room hint) are kept for future use.
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class Config:
    """In-memory representation of the config file."""

    path: Path
    profiles: dict[str, Profile] = field(default_factory=dict)
    default: str = DEFAULT_PROFILE

    def get(self, name: str | None = None) -> Profile:
        """Return the named profile (or the default).

        Creates an empty default profile on demand so first-run callers don't
        have to special-case the "no config yet" situation.
        """
        name = name or self.default
        if name not in self.profiles:
            # No config file? Build an empty in-memory profile so callers get
            # sensible defaults.  It will be persisted on the first save.
            return Profile(name=name)
        return self.profiles[name]

    def upsert(self, profile: Profile) -> None:
        self.profiles[profile.name] = profile

    def to_toml(self) -> str:
        """Serialise the config to a TOML string."""

        lines: list[str] = []
        lines.append("# trs CLI / SDK configuration")
        lines.append("# Generated by `trs config save` - safe to edit by hand.")
        lines.append(f'default = "{self.default}"')
        lines.append("")
        for name in sorted(self.profiles):
            p = self.profiles[name]
            lines.append(f"[profile.{name}]")
            lines.append(f'base_url = "{p.base_url}"')
            if p.token:
                lines.append(f'token = "{p.token}"')
            if p.api_key:
                lines.append(f'api_key = "{p.api_key}"')
            if p.room_cookie:
                lines.append(f'room_cookie = "{p.room_cookie}"')
            for k, v in p.extra.items():
                if isinstance(v, str):
                    lines.append(f'{k} = "{v}"')
                else:
                    lines.append(f"{k} = {v}")
            lines.append("")
        return "\n".join(lines)


def load_config(path: Path | None = None) -> Config:
    """Read the config from disk; return an empty Config if absent."""

    cfg_path = path or _config_path()
    if not cfg_path.exists():
        return Config(path=cfg_path, profiles={}, default=DEFAULT_PROFILE)

    with cfg_path.open("rb") as f:
        data = tomllib.load(f)

    profiles: dict[str, Profile] = {}
    default = DEFAULT_PROFILE
    for name, body in data.items():
        if name == "default":
            if isinstance(body, str):
                default = body
            continue
        # ``[profile.foo]`` may be parsed either as the dotted key
        # ``"profile.foo"`` (older toml libs) or as a nested table
        # ``{"profile": {"foo": {...}}}`` (current spec).  Handle both.
        if name == "profile" and isinstance(body, dict):
            for pname, pbody in body.items():
                if not isinstance(pbody, dict):
                    continue
                base_url = str(pbody.get("base_url", "http://127.0.0.1:8000"))
                token = str(pbody.get("token", ""))
                api_key = str(pbody.get("api_key", ""))
                room_cookie = str(pbody.get("room_cookie", ""))
                extra = {k: v for k, v in pbody.items() if k not in {"base_url", "token", "api_key", "room_cookie"}}
                profiles[pname] = Profile(name=pname, base_url=base_url, token=token,
                                           api_key=api_key, room_cookie=room_cookie, extra=extra)
            continue
        if not isinstance(body, dict):
            continue
        prof_name = name.split(".", 1)[1] if name.startswith("profile.") else name
        base_url = str(body.get("base_url", "http://127.0.0.1:8000"))
        token = str(body.get("token", ""))
        api_key = str(body.get("api_key", ""))
        room_cookie = str(body.get("room_cookie", ""))
        extra = {k: v for k, v in body.items() if k not in {"base_url", "token", "api_key", "room_cookie"}}
        profiles[prof_name] = Profile(name=prof_name, base_url=base_url, token=token,
                                       api_key=api_key, room_cookie=room_cookie, extra=extra)
    if default not in profiles:
        # Allow `default = "x"` to point at a profile that hasn't been created
        # yet; the caller will materialise an empty Profile on demand.
        pass
    return Config(path=cfg_path, profiles=profiles, default=default)


def save_config(cfg: Config, path: Path | None = None) -> Path:
    """Persist the config to disk, creating parent directories as needed."""

    target = path or cfg.path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(cfg.to_toml(), encoding="utf-8")
    # 0o600 on POSIX so tokens aren't world-readable.
    if os.name != "nt":
        try:
            target.chmod(0o600)
        except OSError:
            pass
    return target


def active_profile_name() -> str:
    """Return the profile name selected by env or default."""

    return os.environ.get(PROFILE_ENV) or DEFAULT_PROFILE
